### ISSUE TITLE
Reconnection Issues

### ISSUE THREAD

**Issue by Lindahl** [vsslctrl/integration.home-assistant#3]
For A.6x, the current version of vsslctrl fails to correctly change the stream between Analog 1 and Stream sources. It never works.

This is reliably working in 0.1.5.dev1. I have since used HACS to revert back to 0.1.5.dev1.

I wonder if its because the old version not only sets the source, but also sets the input priority accordingly? And the new version no longer sets the input priority?

Let me know if you want me to turn on debugging and/or capture anything from logs.

**Comment by vsslctrl** [comment]
Hi Lindahl,

Thanks for the report. 

I just tested on my A.3x and the device shows it has changed the source (though I cant physically test it since I dont have anything to connect to it).

The code still changes the priority when changing between [stream and analog sources](https://github.com/vsslctrl/integration.home-assistant/blob/be7d9c191e79ccacb4253795cfec73ec265acd0f/custom_components/vsslctrl/media_player.py#L276). There has been some changes in vsslctrl around sources to support the original A series, though this shouldn't affect us in this case.

Could you please run the debug as explained in this comment and the play around changing the sources: https://github.com/vsslctrl/integration.home-assistant/issues/2#issuecomment-2187954515

It would be great if you can send me a log on 0.1.5.dev1 and 0.1.10.dev1.

Just for good measure, please restart your device too.

**Comment by vsslctrl** [comment]
Hi Lindahl,

Any update on this? Otherwise I will close the issue.

Cheers

**Comment by Lindahl** [comment]
See the debug log - I renamed it from .bin to .txt so I could uplaod to Github:
[error_log.txt](https://github.com/user-attachments/files/18493109/error_log.txt)

I've found that I can reliably get things working again when I reload the integration:
![Image](https://github.com/user-attachments/assets/54910815-9400-42b0-b2a9-3c6cd5cc127a)

After reloading, it works well for a day or so, and then it stops working and I need to reload the integration again. Does the integration try to maintain a constant connection with the VSSL device? Maybe it needs to reconnect periodically to the device for reliable operation, due to software bugs on the device (not necessarily the integration, itself).

**Comment by vsslctrl** [comment]
Hi @Lindahl,

Thanks for the log.

Yes, the integration does try to maintain an open connection to the device (vsslctrl actually) and will reconnect if it doesn't receive a keep-alive response. 

I can't be sure at this point exactly what this is, but could you please try to update to the [latest](https://github.com/vsslctrl/integration.home-assistant/releases/tag/0.1.14.dev1) and do some more testing.

I have changed some code which might help with this issue.

Cheers

**Comment by Lindahl** [comment]
> I can't be sure at this point exactly what this is, but could you please try to update to the latest and do some more testing.

I tried updating. However, it doesn't work, as the integration fails to load due to an error (see attached log for more details):
[error_log-1.txt](https://github.com/user-attachments/files/18523734/error_log-1.txt)

```
2025-01-23 09:25:28.479 ERROR (MainThread) [custom_components.vsslctrl] 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/config/custom_components/vsslctrl/__init__.py", line 27, in async_setup_entry
    model = DeviceModels.get_model_by_name(entry.data.get(MODEL))
  File "/usr/local/lib/python3.13/site-packages/vsslctrl/device.py", line 326, in get_model_by_name
    name_cleaned = name.lower().replace(".", "")
                   ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
2025-01-23 09:25:28.486 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry VSSL A.6x for vsslctrl
Traceback (most recent call last):
  File "/config/custom_components/vsslctrl/__init__.py", line 27, in async_setup_entry
    model = DeviceModels.get_model_by_name(entry.data.get(MODEL))
  File "/usr/local/lib/python3.13/site-packages/vsslctrl/device.py", line 326, in get_model_by_name
    name_cleaned = name.lower().replace(".", "")
                   ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vsslctrl/__init__.py", line 41, in async_setup_entry
    await vssl.shutdown()
          ^^^^
```

Do you want me to open a new issue for this error?

> will reconnect if it doesn't receive a keep-alive response.

I wonder if it still receives keep-alive, but a bug on the VSSL device, itself, is causing it to not take action on received commands? 

> the integration does try to maintain an open connection to the device (vsslctrl actually) 

What is vsslctrl? I would have thought the integration connects directly to the device? Or is vsslctrl the component that the integration creates to connect to the device?

**Comment by vsslctrl** [comment]
> I tried updating. However, it doesn't work, as the integration fails to load due to an error (see attached log for more details):
[error_log-1.txt](https://github.com/user-attachments/files/18523734/error_log-1.txt)

Can you delete the integration and re-add it please or try re-add the entry. It looks like your configuration doesn't have the device model, which wasn't required in previous versions.

![image](https://github.com/user-attachments/assets/48ec3063-28c3-416c-b5eb-e7d1a9c10113)

> I wonder if it still receives keep-alive, but a bug on the VSSL device, itself, is causing it to not take action on received commands?

Once we get you updated, we can do some more testing. I have a A.3x and am also using this daily so trying to reproduce your issue.

> What is vsslctrl? I would have thought the integration connects directly to the device? Or is vsslctrl the component that the integration creates to connect to the device?

Correct, vsslctrl is the component which does all the work (I also maintain vsslctrl)

**Comment by Lindahl** [comment]
I've deleted the device, then download 0.1.14.dev1, restarted HA, and then added the device back. Seems to be working for now.  I've disabled my nightly reload of the integration, so we'll see if it stays stable and operational over the next few days.

**Comment by vsslctrl** [comment]
Great @Lindahl!

**Comment by Lindahl** [comment]
I still have the problem. I need to reload the integration periodically because the VSSL actions don't seem to do anything. I forgot to enable debug, but will try that next time it happens (should be another day or so).

Here are some relevant log messages in the HA logs:

![Image](https://github.com/user-attachments/assets/d9ccd8e0-f27d-499c-b4f5-fa840a2e53c7)

![Image](https://github.com/user-attachments/assets/a4e4b0c4-8924-4391-8bb5-787059e54eac)

**Comment by vsslctrl** [comment]
Do you control your device using any of the VSSL apps on iOS or android?

I have found that if more than one device is trying to control the device sometimes it has a connection issue. This is mostly the new VSSL app, "VSSL Legacy" app doesn't seem to cause an issue as much.

When you test, can you try and avoid using any of the VSSL apps and see if the connection improves.

**Comment by Lindahl** [comment]
I don't use the VSSL app except for setup. So I haven't used it since Friday. I reboot the VSSL every night, I wonder if that's causing the integration problems? What do you do to guarantee reliability of the device connection? Maybe the integration reconnects too early in the device's boot cycle?

**Comment by vsslctrl** [comment]
I just rebooted my VSSL with the debug running and didn't have any issues with the integration reconnecting back to the device once it booted.

The integration connection logic is designed to keep the connection open. If device is on, it will connect on two different ports and keep those connections open by sending and receiving keep-alive messages back and forth. If no message is received within 10 seconds it will try to do a complete new reconnection.

It will keep trying to reconnect indefinitely, in steps of incrementing 15 seconds to a maximum of 5mins.

If your device is off when the integration is reloaded, HA will keep trying to reload the integration and re-establish the connection.

You shouldn't need to reboot your VSSL, I never reboot mine.

Here is the log of what mine just did: [reboot-excerpt-log.txt](https://github.com/user-attachments/files/18556910/reboot-excerpt-log.txt)

If you run vsslctrl debug then we can try and take a look.

Can you also confirm that the source selection is working correctly? So I can rename the issue.

**Comment by Lindahl** [comment]
> You shouldn't need to reboot your VSSL, I never reboot mine.

I've had some issues with Cast in the past that a reboot has fixed, so I just reboot it nightly to start off the day in a good state.

> If you run vsslctrl debug then we can try and take a look.
> Can you also confirm that the source selection is working correctly? So I can rename the issue.

Will do when I encounter this issue again.

**Comment by Lindahl** [comment]
Looks like in the current version, I get unavailable speaker zones periodically. 

See attached error log: [error_log.txt](https://github.com/user-attachments/files/18624792/error_log.txt)

My workaround of reloading the integration fixes the issue.

![Image](https://github.com/user-attachments/assets/83873c0d-815b-4965-bbb9-59d30d46d0dd)

**Comment by vsslctrl** [comment]
When the integration disconnects from a zone, that zones will become "unavailable" until its reconnects.

Now looking through your logs, it looks like other integrations are also disconnecting so I think you might have some network issues.

Is it possible you have a failing network card or congestion on your switch?

You can so some tests from a wired computer using the `ping` command. 
Heres a link that might help, if your not familiar: https://blog.paessler.com/how-to-use-ping-for-troubleshooting

**Comment by Lindahl** [comment]
Those devices are in the garage, and far away from the network. VSSL is
close. I wouldn't think network issues. I don't have those problems with
anything in the house, not even the garage devices, so they're just
temporary blips. I see peer connection reset on those, so it might even be
intentional.

**Comment by Lindahl** [comment]
Overall the network and devices on it has been bulletproof since we moved
in, last June.

**Comment by Lindahl** [comment]
> When the integration disconnects from a zone, that zones will become "unavailable" until its reconnects.

Yeah, I'm wondering if the integration being disconnected from the zone is a result of a nightly reboot? And the integration tries to connect to early in the VSSL's boot process and can't connect correctly? A simple retry mechanism could resolve this issue?

**Comment by vsslctrl** [comment]
The integration already has a reconnection mechanism.

Can you turn on vsslctrl debugging and integration debug logging then reboot your device - leave the debugging running for 10mins after reboot then send me the log.

What is your network setup? My integration doesnt break because I reboot my device - its been designed to keep reconnecting as you would expect.

Also, how are you restarting your A.6x?

**Comment by vsslctrl** [comment]
Hi @Lindahl,

I have just pushed a new update to vsslctrl, which has a revised reconnection mechanism. Hope this satisfies the issue.

I will close this topic for now.
